name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
jobs:
  car-build:
    name: car-build
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.21

      - name: Gradle Build
        run: cd CarsService && ./gradlew build --exclude-task test

      - name: Build image
        run: cd CarsService && docker build -t car_service . --tag antonidass/rsoi2-car-service:latest

      - name: Publish Docker image
        env:
          DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USR}" --password-stdin
          docker push antonidass/rsoi2-car-service:latest

  car-unit-test:
    runs-on: ubuntu-latest
    environment: Deploy
    needs: [car-build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 1.21
      - name: Gradle Test
        run: cd CarsService && ./gradlew test

  payment-build:
    name: payment-build
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.21

      - name: Gradle Build
        run: cd PaymentService && ./gradlew build --exclude-task test

      - name: Build image
        run: cd PaymentService && docker build -t payment_service . --tag antonidass/rsoi2-payment-service:latest

      - name: Publish Docker image
        env:
          DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USR}" --password-stdin
          docker push antonidass/rsoi2-payment-service:latest

  payment-unit-test:
    runs-on: ubuntu-latest
    environment: Deploy
    needs: [payment-build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 1.21
      - name: Gradle Test
        run: cd PaymentService && ./gradlew test

  rental-build:
    name: rental-build
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.21

      - name: Gradle Build
        run: cd RentalService && ./gradlew build --exclude-task test

      - name: Build image
        run: cd RentalService && docker build -t rental_service . --tag antonidass/rsoi2-rental-service:latest

      - name: Publish Docker image
        env:
          DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USR}" --password-stdin
          docker push antonidass/rsoi2-rental-service:latest

  rental-unit-test:
    runs-on: ubuntu-latest
    environment: Deploy
    needs: [rental-build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 1.21
      - name: Gradle Test
        run: cd RentalService && ./gradlew test

  gateway-build:
    name: gateway-build
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.21

      - name: Maven Build
        run: cd GatewayService && mvn -B clean package -DskipTests

      - name: Build image
        run: cd GatewayService && docker build -t gateway_service . --tag antonidass/rsoi2-gateway-service:latest

      - name: Publish Docker image
        env:
          DOCKERHUB_USR: ${{ secrets.DOCKERHUB_USR }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USR}" --password-stdin
          docker push antonidass/rsoi2-gateway-service:latest

  gateway-unit-test:
    runs-on: ubuntu-latest
    environment: Deploy
    needs: [gateway-build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 1.21
      - name: Maven Test
        run: cd GatewayService && mvn -B test
  deploy:
    name: deploy
    environment: Deploy
    runs-on: ubuntu-latest
    needs:
      [car-unit-test, payment-unit-test, rental-unit-test, gateway-unit-test]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Move to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USR }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "postgres,docker-compose.yml"
          target: /opt/car-rental-service

      - name: Run app on VM
        uses: appleboy/ssh-action@v1.0.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USR }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            cd /opt/car-rental-service
            docker compose up --build -d --force-recreate
  # autograding:
  #   name: autograding
  #   environment: Deploy
  #   runs-on: ubuntu-latest
  #   needs: [car-unit-test]
  #   steps:
  #     - name: Run API Tests
  #       uses: matt-ball/newman-action@master
  #       with:
  #         collection: postman/[inst] Lab1.postman_collection.json
  #         environment: postman/[inst][heroku] Lab1.postman_environment.json
  #         delayRequest: 100
  #         reporters: '[ "cli" ]'

  #     - name: Autograding
  #       uses: education/autograding@v1
  #       continue-on-error: true

  #     - name: Github auto grader mark
  #       uses: Romanow/google-sheet-autograder-marker@v1.0
  #       with:
  #         google_token: ${{secrets.GOOGLE_API_KEY}}
  #         sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
  #         homework_number: 1
  #         user_column: "D"
  #         column_offset: "F"
  #         mark: "'+"
